name: yarn build and release

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    branches:
      - main

jobs1:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: ./build.sh --release
        timeout-minutes: 180

      - name: upload
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          bodyFile: "release.md"
          replacesArtifacts: true
          allowUpdates: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Cache node_modules and Yarn cache
        id: cache-node
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: build
        run: ./build.sh

      - name: upload
        uses: ncipollo/release-action@v1
        with:
          artifacts: "oss-browser.tar.gz"
          replacesArtifacts: true
          allowUpdates: true
