name: yarn build and release

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Cache node_modules and Yarn cache
        id: cache-node
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: build
        run: ./build.sh

      - name: delete old auto-build
        run: gh release delete auto-build --cleanup-tag || true; git push origin --delete tag auto-build || true
        env:
          GH_TOKEN: ${{ github.token }}

      - name: upload
        uses: ncipollo/release-action@v1
        with:
          tag: auto-build
          artifacts: "oss-browser.tar.gz"
          replacesArtifacts: true
          allowUpdates: true
