name: yarn build and release

on:
  release:
    types: [published]
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Cache node_modules and Yarn cache
        id: cache-node
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: build
        run: ./build.sh

      - name: Set dynamic tag
        id: set_tag
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-8)
          DATE=$(TZ=UTC-8 date +'%Y%m%d')
          echo "TAG_NAME=autobuild-$DATE-$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: upload
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.set_tag.outputs.TAG_NAME }}
          artifacts: "oss-browser.tar.gz"
          replacesArtifacts: true
          allowUpdates: true
